[project]
name = "learned-preplay"
version = "0.1.0"
description = "An implementation of the MuZero algorithm"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beartype>=0.20.0",
    "distrax>=0.1.5",
    "equinox>=0.11.11",
    "housemaze",
    "ipykernel>=6.29.5",
    "jax>=0.5.0 ; sys_platform != 'linux'",
    "jax[cuda12]>=0.5.0 ; sys_platform == 'linux'",
    "jaxtyping>=0.2.36",
    "mctx>=0.0.5",
    "omegaconf>=2.3.0",
    "optax>=0.2.4",
    "pygraphviz>=1.14 ; sys_platform != 'linux'",
    "rlax>=0.1.6",
    "wandb[media]>=0.19.4",
]

[project.scripts]
muzero = "experiments.muzero:main"

[tool.uv]
package = true

[[tool.uv.index]]
name = "jax"
url = "https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/"

[tool.uv.sources]
optax = { git = "https://github.com/google-deepmind/optax.git" }
housemaze = { git = "https://github.com/adzcai/JaxHouseMaze.git" }

[tool.ruff.lint]
select = [ "E", "F", "I" ]
ignore = ["F722"]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "pre-commit>=4.2.0",
    "pytest>=8.4.0",
]
