[project]
name = "learned-preplay"
version = "0.1.0"
description = "An implementation of the MuZero algorithm"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "distrax>=0.1.5",
    "equinox>=0.11.11",
    "gymnax>=0.0.8",
    "ipykernel>=6.29.5",
    "jaxtyping>=0.2.36",
    "mctx>=0.0.5",
    "pygraphviz>=1.14",
    "pytest>=8.3.4",
    "rlax>=0.1.6",
    "typeguard>=2.13.3",
    "wandb[media]>=0.19.4",
]

[tool.ruff]
line-length = 100
ignore = ["F722"]
