arch:
  projection_kind: mlp
  rnn_size: 48
  mlp_size: 48
  mlp_depth: 1
  goal_dim: 4
  activation: relu

env:
  name: MultiCatch
  source: custom
  kwargs:
    num_goals: 1

collection:
  num_envs: 32
  num_transitions_per_env: 10
  mcts_depth: null
  num_mcts_simulations: 5

value:
  num_value_bins: 81
  min_value: -10.0
  max_value: 10.0

bootstrap:
  discount: 0.988
  lambda_gae: 0.95

lr:
  init_value: 0.0
  peak_value: 0.001
  warmup_steps: 1_000
  transition_steps: 1_000
  decay_rate: 0.1
  staircase: True
  end_value: 0.00001

buffer:
  num_transitions_per_env: 100_000
  priority_exponent: 0.9
  importance_exponent: 0.6

optim:
  num_updates: 10_000
  num_updates_per_minibatch: 4
  batch_size: 64
  num_time_steps: 20
  max_grad_norm: 3.14

  target_update_freq: 100
  target_update_size: 1.0
  world_model_gradient_scale: 0.5
  reanalyze_ratio: 0.5

loss:
  policy_coef: 1.0
  value_coef: 0.25
  # model_policy_coef: 10.0
  # model_value_coef: 2.5
  reward_coef: 1.0

eval:
  warnings: False
  num_evals: 12
  num_eval_envs: 2
  num_time_steps: 25
