arch:
  projection_kind: mlp
  rnn_size: 128
  mlp_size: 48
  mlp_depth: 1
  goal_dim: 4
  activation: relu

env:
  name: MultiCatch
  source: custom
  kwargs:
    num_goals: 2

collection:
  total_transitions: 100000
  num_envs: 64
  buffer_size_denominator: 1
  num_timesteps: 10
  mcts_depth: 10
  num_mcts_simulations: 8

value:
  num_value_bins: 7
  min_value: -1.0
  max_value: 1.0

bootstrap:
  discount: 0.997
  lambda_gae: 0.95
  target_update_freq: 4
  target_update_size: 0.99

optim:
  num_minibatches: 8
  batch_size: 64
  num_timesteps: 20
  p_reanalyze: 0.0
  max_grad_norm: 3.14

  lr: 0.1
  warmup_frac: 0.1
  decay_rate: 0.5
  num_stairs: 12

  value_coef: 0.5
  reward_coef: 0.99
  world_model_gradient_scale: 0.5
  priority_exponent: 0.8
  importance_exponent: 0.0

eval:
  warnings: False
  num_evals: 8
  num_eval_envs: 2
  num_timesteps: 25
