arch:
  projection_kind: mlp
  rnn_size: 128
  mlp_size: 48
  mlp_depth: 1
  goal_dim: 4
  activation: relu

env:
  name: MultiCatch
  source: custom
  kwargs:
    num_goals: 2

collection:
  total_transitions: 200_000
  num_envs: 64
  num_buffer_fills: 2
  num_time_steps: 10
  mcts_depth: 10
  num_mcts_simulations: 4

value:
  num_value_bins: 9
  min_value: -1.0
  max_value: 1.0

bootstrap:
  discount: 0.988
  lambda_gae: 0.95

lr:
  lr_init: 0.05
  warmup_frac: 0.1
  decay_rate: 0.75
  num_stairs: 8

optim:
  num_minibatches: 8
  batch_size: 64
  num_time_steps: 20
  max_grad_norm: 3.14

  target_update_freq: 2500
  target_update_size: 0.99
  world_model_gradient_scale: 0.5
  priority_exponent: 0.8
  importance_exponent: 0.0

loss:
  value_coef: 0.5
  reward_coef: 0.99

eval:
  warnings: False
  num_evals: 12
  num_eval_envs: 2
  num_time_steps: 25
