arch:
  projection_kind: mlp
  dyn_size: 48
  mlp_size: 32
  mlp_depth: 1
  goal_dim: 4
  activation: relu
  world_model_gradient_scale: 0.5

env:
  name: MultiCatch
  source: custom
  kwargs:
    num_goals: 1

mcts:
  num_simulations: 5
  max_depth: null

value:
  num_value_bins: 9
  min_value: -1.0
  max_value: 1.0

bootstrap:
  discount: 0.988
  lambda_gae: 0.95

buffer:
  batch_size: 32
  max_length: 10_000
  sample_length: 20

replay:
  priority_exponent: 0.9
  importance_exponent: 0.6

lr:
  init_value: 0.0
  peak_value: 0.01
  warmup_steps: 1_000
  transition_steps: 10_000
  decay_rate: 0.5
  staircase: True

optim:
  total_updates: 10_000
  num_updates_per_minibatch: 4
  batch_size: 64
  target_update_freq: 100

loss:
  policy_coef: 1.0
  value_coef: 0.25
  # model_policy_coef: 10.0
  # model_value_coef: 2.5
  reward_coef: 1.0

eval:
  warnings: False
  eval_freq: 100
