arch:
  projection_kind: mlp
  dyn_size: 1
  mlp_size: 1
  mlp_depth: 0
  goal_dim: 1
  activation: relu
  world_model_gradient_scale: 0.5

env:
  name: dummy
  source: custom
  kwargs:
    max_horizon: 1

mcts:
  num_simulations: 1
  max_depth: null

value:
  num_value_bins: 2
  min_value: 0.0
  max_value: 1.0

bootstrap:
  discount: 0.988
  lambda_gae: 0.95

buffer:
  batch_size: 4
  max_length: 100
  sample_length: 2

replay:
  priority_exponent: 0.9
  importance_exponent: 0.6

lr:
  init_value: 0.0
  peak_value: 0.1
  warmup_steps: 10
  transition_steps: 10
  decay_rate: 0.5
  staircase: True

optim:
  total_updates: 100
  num_updates_per_minibatch: 1
  batch_size: 4
  target_update_freq: 100

loss:
  policy_coef: 0.0
  value_coef: 1.0
  reward_coef: 0.0

eval:
  warnings: False
  eval_freq: 1000
