arch:
  kind: mlp
  rnn_size: 128
  mlp_size: 64
  mlp_depth: 1
  activation: relu

env:
  env_name: Catch-bsuite
  env_source: gymnax
  horizon: 9

collection:
  total_transitions: 200000
  num_envs: 64
  mcts_depth: ${env.horizon}
  num_mcts_simulations: 4

value:
  num_value_bins: 7
  min_value: -1.0
  max_value: 1.0

bootstrap:
  discount: 0.997
  lambda_gae: 0.95
  target_update_freq: 4
  target_update_size: 0.75

optim:
  num_minibatches: 8
  batch_size: 32
  lr_init: 0.01
  max_grad_norm: 3.14
  value_coef: 0.6
  reward_coef: 0.8
  priority_exponent: 0.8

eval:
  warnings: False
  num_evals: 8
  num_eval_envs: 2
