arch:
  kind: mlp
  rnn_size: 128
  mlp_size: 64
  mlp_depth: 1
  goal_dim: 2
  activation: relu

env:
  name: MultiCatch
  source: custom
  kwargs:
    num_goals: 2

collection:
  total_transitions: 100000
  num_envs: 64
  timesteps: 10
  mcts_depth: 10
  num_mcts_simulations: 4

value:
  num_value_bins: 7
  min_value: -1.0
  max_value: 1.0

bootstrap:
  discount: 0.997
  lambda_gae: 0.95
  target_update_freq: 4
  target_update_size: 0.99

optim:
  num_minibatches: 8
  batch_size: 64
  timesteps: 20
  lr_init: 0.01
  max_grad_norm: 3.14
  value_coef: 0.5
  reward_coef: 0.99
  priority_exponent: 0.8
  importance_exponent: 0.0

eval:
  warnings: False
  num_evals: 8
  num_eval_envs: 2
  timesteps: 25
