arch:
  projection_kind: housemaze
  rnn_size: 32
  mlp_size: 32
  mlp_depth: 2
  goal_dim: 8
  action_dim: 8
  activation: relu

env:
  name: HouseMaze
  source: custom

collection:
  total_transitions: 100000
  num_envs: 8
  num_timesteps: 50
  buffer_size_denominator: 4.0
  mcts_depth: 10
  num_mcts_simulations: 4

value:
  num_value_bins: 7
  min_value: -1.0
  max_value: 1.0

bootstrap:
  discount: 0.997
  lambda_gae: 0.95
  target_update_freq: 4
  target_update_size: 0.99

optim:
  num_minibatches: 8
  batch_size: 64
  num_timesteps: 200
  lr_init: 0.01
  max_grad_norm: 3.14
  value_coef: 0.5
  reward_coef: 0.99
  priority_exponent: 0.8
  importance_exponent: 0.0

eval:
  warnings: False
  num_evals: 8
  num_eval_envs: 2
  num_timesteps: 25
